---

- block:
  - name: Include environment specific vars
    include_vars:
      file: "roles/ret/vars/{{ env }}.yml"

  - name: Create work directory
    tempfile:
      state: directory
      suffix: deploy
    register: work_dir

  - name: Write Reticulum config file
    template:
      src: reticulum.toml.j2
      dest: "{{ work_dir.path }}/reticulum.toml"

  - name: Write DD agent config file
    template:
      src: dd-agent.toml.j2
      dest: "{{ work_dir.path }}/dd-agent.toml"

  - name: Deploy Reticulum configs
    shell: "cat {{ work_dir.path }}/reticulum.toml | /hab/pkgs/mozillareality/hab-butterfly/0.39.1/20171118004554/bin/hab-butterfly config apply --peer $(curl -s http://169.254.169.254/latest/meta-data/local-ipv4) --org mozillareality --ring mr reticulum.default $(date +%s)"

  - name: Deploy Datadog Agent configs
    shell: "cat {{ work_dir.path }}/dd-agent.toml | /hab/pkgs/mozillareality/hab-butterfly/0.39.1/20171118004554/bin/hab-butterfly config apply --peer $(curl -s http://169.254.169.254/latest/meta-data/local-ipv4) --org mozillareality --ring mr dd-agent.default $(date +%s)"

  always:
  - name: Remove work directory
    file:
      path: "{{ work_dir.path }}"
      state: absent
