---

- block:
  - name: Include environment specific secrets
    include_vars:
      file: "{{ secrets_path }}/roles/discord/vars/{{ env }}.yml"

  - name: Include environment specific vars
    include_vars:
      file: "roles/discord/vars/{{ env }}.yml"

  - name: Install moz hab-butterfly (needed until https://github.com/habitat-sh/habitat/issues/4066 is closed)
    shell: "hab pkg install mozillareality/hab-butterfly"
    when: env != 'local'

  - name: Create work directory
    tempfile:
      state: directory
      suffix: deploy
    register: work_dir

  - name: "Write config"
    template:
      src: "{{ item }}.toml.j2"
      dest: "{{ work_dir.path }}/{{ item }}.toml"
    loop: "{{ services }}"

  - name: "Deploy remote configs"
    shell: "cat {{ work_dir.path }}/{{ item }}.toml | /hab/pkgs/mozillareality/hab-butterfly/0.39.1/20171118004554/bin/hab-butterfly config apply --peer $(curl -s http://169.254.169.254/latest/meta-data/local-ipv4) --org mozillareality --ring mr {{ item }}.default $(date +%s)"
    when: env != 'local'
    loop: "{{ services }}"

  - name: "Make local target config dir"
    shell: "mkdir -p /hab/user/{{ item }}/config"
    when: env == 'local'
    loop: "{{ services }}"

  - name: "Copy local config"
    shell: "cp {{ work_dir.path }}/{{ item }}.toml /hab/user/{{ item }}/config/user.toml"
    when: env == 'local'
    loop: "{{ services }}"

  always:
  - name: Remove work directory
    file:
      path: "{{ work_dir.path }}"
      state: absent
