---

- block:
  - name: Include environment specific secrets
    include_vars:
      file: "{{ secrets_path }}/roles/migrate/vars/{{ env }}.yml"

  - name: Include environment specific vars
    include_vars:
      file: "roles/migrate/vars/{{ env }}.yml"

  - name: Create work directory
    tempfile:
      state: directory
      suffix: deploy
    register: work_dir

  - name: Checkout hubs-ops
    git:
      repo: "{{ ops_repo }}"
      dest: "{{ work_dir.path }}"

  - name: "Write configs"
    template:
      src: "flyway.conf.j2"
      dest: "{{ work_dir.path }}/db/{{ item }}/conf/flyway.conf"
    loop: "{{ schemas }}"

  - name: Baseline schemas
    shell: "docker run --mount type=bind,source={{ work_dir.path }}/db/{{ item }}/conf,target=/conf --mount type=bind,source={{ work_dir.path }}/db/{{ item }}/sql,target=/sql --network=host --rm boxfuse/flyway -configFiles=/conf/flyway.conf baseline"
    args:
      chdir: "{{ work_dir.path }}/db/{{ item }}"
    loop: "{{ schemas }}"

  - name: Migrate schemas
    shell: "docker run --mount type=bind,source={{ work_dir.path }}/db/{{ item }}/conf,target=/conf --mount type=bind,source={{ work_dir.path }}/db/{{ item }}/sql,target=/sql --network=host --rm boxfuse/flyway -configFiles=/conf/flyway.conf migrate"
    args:
      chdir: "{{ work_dir.path }}/db/{{ item }}"
    loop: "{{ schemas }}"

  always:
  - name: Remove work directory
    file:
      path: "{{ work_dir.path }}"
      state: absent
